# Generated by Django 4.2.1 on 2023-07-02 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_boutique_category_boutiques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='boutiques',
        ),
        migrations.DeleteModel(
            name='Boutique',
        ),
    ]
